/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book_management;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tuan.nguyen1
 */
public class Demo_project extends javax.swing.JFrame {

    /**
     * Creates new form Demo_project
     */
    public Demo_project() {
 
        setTitle("Student Management");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Sign_In = new javax.swing.JButton();
        btSignup = new javax.swing.JButton();
        Title3 = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        Imagine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title1.setFont(new java.awt.Font("Traditional Arabic", 3, 42)); // NOI18N
        Title1.setText("Welcome to   ");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        Title2.setFont(new java.awt.Font("Traditional Arabic", 3, 30)); // NOI18N
        Title2.setText("The intelligent book managerment program");
        getContentPane().add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 600, -1));

        Sign_In.setBackground(new java.awt.Color(0, 255, 255));
        Sign_In.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sign_In.setText("Sign In");
        Sign_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_InActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 110, 40));

        btSignup.setBackground(new java.awt.Color(51, 255, 255));
        btSignup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSignup.setText("Sign Up");
        btSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 110, 40));

        Title3.setFont(new java.awt.Font("Traditional Arabic", 3, 30)); // NOI18N
        Title3.setText("The intelligent book managerment program");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 600, -1));

        btExit.setBackground(new java.awt.Color(51, 255, 255));
        btExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btExit.setText("Exit ");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, 40));

        Imagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_management/thuvien2.jpg"))); // NOI18N
        getContentPane().add(Imagine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_InActionPerformed
        // TODO add your handling code here:
        Sign_In signin;
        try {
            signin = new Sign_In();
            signin.setVisible(true);
            signin.pack();
            signin.setLocationRelativeTo(null);
            signin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Demo_project.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_Sign_InActionPerformed

    private void btSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignupActionPerformed
        try {
            Sign_Up signup = new Sign_Up();
            signup.setVisible(true);
            signup.pack();
            signup.setLocationRelativeTo(null);
            signup.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Demo_project.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSignupActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
       int  a = JOptionPane.showConfirmDialog(rootPane, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo_project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagine;
    private javax.swing.JButton Sign_In;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btSignup;
    // End of variables declaration//GEN-END:variables
}
